services:
  # Backend service
  server:
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb # Wait for database to be ready

  # Frontend service
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

  # Database service (MongoDB)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persistent volume to retain data

volumes:
  mongo-data: # Named volume for data persistence